### ISSUE TITLE
Couldn't install on python 3.6 windows 7

### ISSUE THREAD

**Issue by hbake001** [wiseman/py-webrtcvad#11]
I got the following error after running the command 
pip install webrtcvad 

```
- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  copying webrtcvad.py -> build\lib.win-amd64-3.6
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\engadmin\AppData\Local\Temp\pip-build-eqlnrdtl\webrtcvad\setu
p.py", line 87, in <module>
      'psutil', 'memory_profiler']
    File "C:\Users\engadmin\Anaconda3\lib\distutils\core.py", line 148, in setup

      dist.run_commands()
    File "C:\Users\engadmin\Anaconda3\lib\distutils\dist.py", line 955, in run_c
ommands
      self.run_command(cmd)
    File "C:\Users\engadmin\Anaconda3\lib\distutils\dist.py", line 974, in run_c
ommand
      cmd_obj.run()
    File "c:\users\engadmin\anaconda3\lib\site-packages\wheel\bdist_wheel.py", l
ine 179, in run
      self.run_command('build')
    File "C:\Users\engadmin\Anaconda3\lib\distutils\cmd.py", line 313, in run_co
mmand
      self.distribution.run_command(command)
    File "C:\Users\engadmin\Anaconda3\lib\distutils\dist.py", line 974, in run_c
ommand
      cmd_obj.run()
    File "C:\Users\engadmin\Anaconda3\lib\distutils\command\build.py", line 135,
 in run
      self.run_command(cmd_name)
    File "C:\Users\engadmin\Anaconda3\lib\distutils\cmd.py", line 313, in run_co
mmand
      self.distribution.run_command(command)
    File "C:\Users\engadmin\Anaconda3\lib\distutils\dist.py", line 974, in run_c
ommand
      cmd_obj.run()
    File "c:\users\engadmin\anaconda3\lib\site-packages\setuptools\command\build
_ext.py", line 75, in run
      _build_ext.run(self)
    File "c:\users\engadmin\anaconda3\lib\site-packages\Cython\Distutils\old_bui
ld_ext.py", line 185, in run
      _build_ext.build_ext.run(self)
    File "C:\Users\engadmin\Anaconda3\lib\distutils\command\build_ext.py", line
308, in run
      force=self.force)
    File "C:\Users\engadmin\Anaconda3\lib\distutils\ccompiler.py", line 1031, in
 new_compiler
      return klass(None, dry_run, force)
    File "C:\Users\engadmin\Anaconda3\lib\distutils\cygwinccompiler.py", line 28
2, in __init__
      CygwinCCompiler.__init__ (self, verbose, dry_run, force)
    File "C:\Users\engadmin\Anaconda3\lib\distutils\cygwinccompiler.py", line 15
7, in __init__
      self.dll_libraries = get_msvcr()
    File "C:\Users\engadmin\Anaconda3\lib\distutils\cygwinccompiler.py", line 86
, in get_msvcr
      raise ValueError("Unknown MS Compiler version %s " % msc_ver)
  ValueError: Unknown MS Compiler version 1900

  ----------------------------------------
  Failed building wheel for webrtcvad
  Running setup.py clean for webrtcvad
Failed to build webrtcvad
Installing collected packages: webrtcvad
  Running setup.py install for webrtcvad ... error
    Complete output from command C:\Users\engadmin\Anaconda3\python.exe -u -c "i
mport setuptools, tokenize;__file__='C:\\Users\\engadmin\\AppData\\Local\\Temp\\
pip-build-eqlnrdtl\\webrtcvad\\setup.py';f=getattr(tokenize, 'open', open)(__fil
e__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__,
'exec'))" install --record C:\Users\engadmin\AppData\Local\Temp\pip-k7jjwudm-rec
ord\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    copying webrtcvad.py -> build\lib.win-amd64-3.6
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\engadmin\AppData\Local\Temp\pip-build-eqlnrdtl\webrtcvad\se
tup.py", line 87, in <module>
        'psutil', 'memory_profiler']
      File "C:\Users\engadmin\Anaconda3\lib\distutils\core.py", line 148, in set
up
        dist.run_commands()
      File "C:\Users\engadmin\Anaconda3\lib\distutils\dist.py", line 955, in run
_commands
        self.run_command(cmd)
      File "C:\Users\engadmin\Anaconda3\lib\distutils\dist.py", line 974, in run
_command
        cmd_obj.run()
      File "c:\users\engadmin\anaconda3\lib\site-packages\setuptools\command\ins
tall.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\engadmin\Anaconda3\lib\distutils\command\install.py", line
545, in run
        self.run_command('build')
      File "C:\Users\engadmin\Anaconda3\lib\distutils\cmd.py", line 313, in run_
command
        self.distribution.run_command(command)
      File "C:\Users\engadmin\Anaconda3\lib\distutils\dist.py", line 974, in run
_command
        cmd_obj.run()
      File "C:\Users\engadmin\Anaconda3\lib\distutils\command\build.py", line 13
5, in run
        self.run_command(cmd_name)
      File "C:\Users\engadmin\Anaconda3\lib\distutils\cmd.py", line 313, in run_
command
        self.distribution.run_command(command)
      File "C:\Users\engadmin\Anaconda3\lib\distutils\dist.py", line 974, in run
_command
        cmd_obj.run()
      File "c:\users\engadmin\anaconda3\lib\site-packages\setuptools\command\bui
ld_ext.py", line 75, in run
        _build_ext.run(self)
      File "c:\users\engadmin\anaconda3\lib\site-packages\Cython\Distutils\old_b
uild_ext.py", line 185, in run
        _build_ext.build_ext.run(self)
      File "C:\Users\engadmin\Anaconda3\lib\distutils\command\build_ext.py", lin
e 308, in run
        force=self.force)
      File "C:\Users\engadmin\Anaconda3\lib\distutils\ccompiler.py", line 1031,
in new_compiler
        return klass(None, dry_run, force)
      File "C:\Users\engadmin\Anaconda3\lib\distutils\cygwinccompiler.py", line
282, in __init__
        CygwinCCompiler.__init__ (self, verbose, dry_run, force)
      File "C:\Users\engadmin\Anaconda3\lib\distutils\cygwinccompiler.py", line
157, in __init__
        self.dll_libraries = get_msvcr()
      File "C:\Users\engadmin\Anaconda3\lib\distutils\cygwinccompiler.py", line
86, in get_msvcr
        raise ValueError("Unknown MS Compiler version %s " % msc_ver)
    ValueError: Unknown MS Compiler version 1900

    ----------------------------------------
Command "C:\Users\engadmin\Anaconda3\python.exe -u -c "import setuptools, tokeni
ze;__file__='C:\\Users\\engadmin\\AppData\\Local\\Temp\\pip-build-eqlnrdtl\\webr
tcvad\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().repla
ce('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --reco
rd C:\Users\engadmin\AppData\Local\Temp\pip-k7jjwudm-record\install-record.txt -
-single-version-externally-managed --compile" failed with error code 1 in C:\Use
rs\engadmin\AppData\Local\Temp\pip-build-eqlnrdtl\webrtcvad\
```

**Comment by wiseman** [comment]
I think you need to install the [version of Visual Studio that Python is expecting](https://www.microsoft.com/en-us/download/details.aspx?id=44266).

**Comment by wiseman** [comment]
I'm pretty sure this isn't a py-webrtcvad issue, so I'm going to close it, but feel free to post more here if you still have problems or are able to resolve it.
