### ISSUE TITLE
Assertion error..Here my sample rate is 44100

### ISSUE THREAD

**Issue by rakeshreddy36** [wiseman/py-webrtcvad#61]
E:\test\py-webrtcvad-master>python example.py 3 version1_1593692350560.wav
Traceback (most recent call last):
  File "example.py", line 158, in <module>
    main(sys.argv[1:])
  File "example.py", line 146, in main
    audio, sample_rate = read_wave(args[1])
  File "example.py", line 20, in read_wave
    assert sample_rate in (8000, 16000, 32000, 48000)
AssertionError

---> IF i add my sample rate of 44100 to    assert sample_rate in (8000, 16000, 32000, 48000, 44100),,below error is coming. 

E:\test\py-webrtcvad-master>python example.py 3 version1_1593692350560.wav
Traceback (most recent call last):
  File "example.py", line 158, in <module>
    main(sys.argv[1:])
  File "example.py", line 151, in main
    for i, segment in enumerate(segments):
  File "example.py", line 99, in vad_collector
    is_speech = vad.is_speech(frame.bytes, sample_rate)
  File "E:\test\py-webrtcvad-master\webrtcvad.py", line 27, in is_speech
    return _webrtcvad.process(self._vad, sample_rate, buf, length)
webrtcvad.Error: Error while processing frame

**Comment by wiseman** [comment]
From the README: "The WebRTC VAD only accepts 16-bit mono PCM audio, sampled at 8000, 16000, 32000 or 48000 Hz."

This is a limitation of the underlying Google code.
